name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build the code
      run: ./gradlew build
    - name: test run
      run: ./gradlew run --args="Apple Apple Orange Apple Apple Orange Orange Orange"
    - name: smaller test run
      run: ./gradlew run --args="Orange Orange Orange Apple"
